name: Codecov

on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v2
        with:
          flags: unittests # optional
          fail_ci_if_error: false # optional (default = false)
          verbose: false # optional (default = false)
          
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v